format_version: 3
pipelines:
  Hello-World-App:
    group: myFirstpipeline
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/htetgit/Hello-World-App.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - App-Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          App-run:
            timeout: 0
            tasks:
            - exec:
                command: docker
                run_if: passed
            - exec:
                arguments:
                - -d
                - -p
                - 8080:8080
                - hello-world:latest
                command: run
                run_if: passed
